// Mirrors docs/design/design-system/tokens.css into src/theme.ts so the app
// and the design system never disagree on a value.
import { readFileSync, writeFileSync } from 'node:fs';

const css = readFileSync('docs/design/design-system/tokens.css', 'utf8');
const colors = {};
const space = {};
const radius = {};
const text = {};
const control = {};
const motion = {};
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const px = (v) => Number.parseInt(v, 10);
for (const [, name, raw] of css.matchAll(/--([a-z0-9-]+):\s*([^;]+);/g)) {
  const value = raw.trim();
  if (name.startsWith('color-')) colors[camel(name.slice(6))] = value;
  else if (name.startsWith('space-')) space[name.slice(6)] = px(value);
  else if (name.startsWith('radius-')) radius[camel(name.slice(7))] = px(value);
  else if (name.startsWith('text-')) {
    // "600 28px/34px var(--font-sans)" or "400 17px/26px ..."
    const m = value.match(/^(\d{3})\s+(\d+)px\/(\d+)px/);
    if (!m) throw new Error(`cannot parse --${name}: ${value}`);
    text[camel(name.slice(5))] = { fontSize: px(m[2]), lineHeight: px(m[3]), fontWeight: m[1] };
  } else if (name === 'control') control.size = px(value);
  else if (name === 'control-big') control.big = px(value);
  else if (name === 'touch-min') control.touchMin = px(value);
  else if (name.startsWith('motion-') && /^\d+ms/.test(value)) motion[camel(name.slice(7))] = px(value);
}
// The one value with no token: the pill button height, from styles.css .btn.
control.button = px(readFileSync('docs/design/design-system/styles.css', 'utf8').match(/\.btn \{ height: (\d+)px/)[1]);
const literal = (o) => JSON.stringify(o, null, 2).replace(/"([a-zA-Z0-9]+)":/g, '$1:');
const out = `// Generated by scripts/tokens-to-ts.mjs from docs/design/design-system/tokens.css. Do not edit.
export const colors = ${literal(colors)} as const;
export const space = ${literal(space)} as const;
export const radius = ${literal(radius)} as const;
export const text = ${literal(text)} as const;
export const control = ${literal(control)} as const;
export const motion = ${literal(motion)} as const;
`;
writeFileSync('src/theme.ts', out);
console.log(`src/theme.ts: ${Object.keys(colors).length} colours, ${Object.keys(space).length} spaces, ${Object.keys(radius).length} radii, ${Object.keys(text).length} text styles, ${Object.keys(control).length} control sizes, ${Object.keys(motion).length} motions`);
