// Mirrors docs/design/design-system/tokens.css into src/theme.ts so the app
// and the design system never disagree on a value.
import { readFileSync, writeFileSync } from 'node:fs';

const css = readFileSync('docs/design/design-system/tokens.css', 'utf8');
const colors = {};
const space = {};
const radius = {};
for (const [, name, value] of css.matchAll(/--([a-z0-9-]+):\s*([^;]+);/g)) {
  const key = name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  if (name.startsWith('color-')) colors[key.slice(5).replace(/^[A-Z]/, (c) => c.toLowerCase())] = value.trim();
  else if (name.startsWith('space-')) space[name.slice(6)] = Number.parseInt(value, 10);
  else if (name.startsWith('radius-')) radius[name.slice(7)] = Number.parseInt(value, 10);
}
const literal = (o) => JSON.stringify(o, null, 2).replace(/"([a-zA-Z0-9]+)":/g, '$1:');
const out = `// Generated by scripts/tokens-to-ts.mjs from docs/design/design-system/tokens.css. Do not edit.
export const colors = ${literal(colors)} as const;
export const space = ${literal(space)} as const;
export const radius = ${literal(radius)} as const;
export const text = {
  title: { fontSize: 28, lineHeight: 34, fontWeight: '600' },
  heading: { fontSize: 20, lineHeight: 26, fontWeight: '600' },
  body: { fontSize: 17, lineHeight: 26 },
  meta: { fontSize: 14, lineHeight: 20 },
  label: { fontSize: 12, lineHeight: 16 },
  button: { fontSize: 17, lineHeight: 26, fontWeight: '600' },
} as const;
export const control = { size: 64, big: 88, button: 56, touchMin: 44 } as const;
export const motion = { press: 160 } as const;
`;
writeFileSync('src/theme.ts', out);
console.log(`src/theme.ts: ${Object.keys(colors).length} colours, ${Object.keys(space).length} spaces, ${Object.keys(radius).length} radii`);
