// Generated by scripts/tokens-to-ts.mjs from docs/design/design-system/tokens.css. Do not edit.
export const colors = {
  surface: "#0B0C0F",
  surfaceRaised: "#1A1C22",
  text: "#F1F2F4",
  textMuted: "#9BA1AC",
  accent: "#6FA3FF",
  onAccent: "#0B0C0F",
  recording: "#E5484D",
  ok: "#8DB898",
  border: "#2A2D35",
  scrim: "rgba(0, 0, 0, 0.6)",
  onRecording: "#FFFFFF"
} as const;
export const space = {
  1: 4,
  2: 8,
  3: 12,
  4: 16,
  6: 24,
  8: 32,
  12: 48
} as const;
export const radius = {
  card: 12,
  pill: 999,
  sheet: 24
} as const;
export const text = {
  title: { fontSize: 28, lineHeight: 34, fontWeight: '600' },
  heading: { fontSize: 20, lineHeight: 26, fontWeight: '600' },
  body: { fontSize: 17, lineHeight: 26 },
  meta: { fontSize: 14, lineHeight: 20 },
  label: { fontSize: 12, lineHeight: 16 },
  button: { fontSize: 17, lineHeight: 26, fontWeight: '600' },
} as const;
export const control = { size: 64, big: 88, button: 56, touchMin: 44 } as const;
export const motion = { press: 160 } as const;
